### ISSUE TITLE
Question about other trained models

### ISSUE THREAD

**Issue by atomoton** [yusuketomoto/chainer-fast-neuralstyle#11]
Are there any places to get trained models with other style images? I'm trying to make a few myself but they take a long long time!

**Comment by atomoton** [comment]
NVM, I just found the repo for them. 

thanks!

**Comment by rushilanirudh** [comment]
Hi @atomoton can you point me to the repo? I'm trying to obtain models for different styles, and it would save  me a lot of time if there are already out there. Thanks!

**Comment by atomoton** [comment]
@rushilanirudh  https://github.com/gafr/chainer-fast-neuralstyle-models

**Comment by rushilanirudh** [comment]
@atomoton awesome, thanks for the link! Don't have any now, but will update if I do come across any :+1:
