### ISSUE TITLE
python3.5 train.py not work

### ISSUE THREAD

**Issue by jawebdev** [yusuketomoto/chainer-fast-neuralstyle#14]
Thanks for FAST neural style engine.
I used python3.5 
$) train.py -s sample_images/style_0.jpg -d models/ -g 0
=> 
FileNotFoundError: [Errno 2] No such file or directory: 'vgg16.model'

I got VGG_ILSVRC_16_layers.caffemodel
but, train.py need vgg16.model.
How can I solve this problem?

**Comment by alexblickenstaff** [comment]
Did you run `setup_model.sh`? That downloads `VGG_ILSVRC_16_layers.caffemodel` (if you don't have it) and then runs `create_chainer_model.py` which turns that caffemodel file into the `vgg16.model` file you need.
