### ISSUE TITLE
I do not understand the Train part, need more explanation

### ISSUE THREAD

**Issue by enzyme69** [yusuketomoto/chainer-fast-neuralstyle#17]
I got the VGG model, and process it. 

But I don't get the part to Train. Is this the part where I point into STYLE and the VGG, and then it will output the new pretrained model?

Train

Need to train one image transformation network model per one style target. According to the paper, the models are trained on the Microsoft COCO dataset.

python train.py -s <style_image_path> -d <training_dataset_path> -g 0

**Comment by ttoinou** [comment]
> But I don't get the part to Train. Is this the part where I point into STYLE and the VGG, and then it will output the new pretrained model?
Yes, you have to download the train 2014 zip and process the 83k images :) !
Good luck ! (it worked for me)

**Comment by enzyme69** [comment]
Ok Thanks!!
