### ISSUE TITLE
Image result size

### ISSUE THREAD

**Issue by jwhscholten** [yusuketomoto/chainer-fast-neuralstyle#23]
Hi, I'm fairly new to these neuralstyle algorithms but is it possible to redraw the result at a higher resolution than the input image?

**Comment by DylanAlloy** [comment]
Not that I know of personally to chime in but check out waifu2x. it's an algorithm designed to upscale images but I've heard there is better stuff out there.

**Comment by bmaltais** [comment]
Here is my method... work pretty well but depend on your original res you want to upscale. I usually bring it to the max I can with it then apply one final waifu2x on it after:

neural_styleb.lua \
-num_iterations 300 -gpu 0 -backend cudnn -cudnn_autotune \
-save_iter 50 -style_scale 1 \
-style_image ../in/art4/<src style image> \
-content_image ../in/art4/<image you want upscaled> \
-output_image ../in/art4/<resulting file> \
-image_size 1100 \
-style_weight 10000000 -init image -content_weight 1000000 -normalize_gradients \
-content_layers relu1,relu2,relu3,relu4,relu5 -style_layers relu1,relu2,relu3,relu4,relu5 \
-model_file models/VGG_CNN_M_1024.caffemodel -proto_file models/VGG_CNN_M_1024_deploy.prototxt
