### ISSUE TITLE
Freezing/Non responsive during training

### ISSUE THREAD

**Issue by DylanAlloy** [yusuketomoto/chainer-fast-neuralstyle#26]
Hey there.

I don't get the epoch indication anymore, it just freezes. Could this be due to the amount of memory I'm attempting to use? I'm doing --image_size 512 and 3 epochs on a very large image with 4GB VRAM from an amazon instance. I have a GTX 1080 but I have problems with booting Ubuntu, though I may have to try it again I guess if this is the result of not enough VRAM.

<img width="513" alt="capture" src="https://cloud.githubusercontent.com/assets/12659763/17314842/3c1ea774-5835-11e6-8a65-40c9abb65319.PNG">

When the freeze happens, CTRL+C does not work to exit the process.

EDIT: Also I'm using test2015/ and not train2014/, which I guess might cause this so I'll go ahead and download train2014 in case that's what it is. I just thought newer=better but now I'm realizing they're actually for different uses.

**Comment by ttoinou** [comment]
Does it work now ?

**Comment by DylanAlloy** [comment]
Yeah I feel silly. I was tired.
