### ISSUE TITLE
Mutiple GPUs support?

### ISSUE THREAD

**Issue by ycjing** [yusuketomoto/chainer-fast-neuralstyle#39]
Thanks for the great code and it works quite well. It only requires less than one second to generate a stylized image. 

My question is, does the code support parallel computation on multiple GPUs? It may be even faster when multiple GPUs work parallelly. If so, what's the maximum number of GPUs it can support?

Thanks!

**Comment by ttoinou** [comment]
I don't know the answer for true parallelization but I think it might be possible to train one model per GPU (or maybe train a two image style on two gpu by regularly swapping models between two gpu) and to generate one model per GPU in parallel. At least the power computation is not lost (a good example would be for images sequence or dividing a big image into multiple block generated in parallel)

**Comment by yusuketomoto** [comment]
The codes doesn’t support multiple GPU parallel computation. In general there are two types of parallel computation: model-parallel and data-parallel. You can implement both types of parallel computation in Chainer referring to [this](http://docs.chainer.org/en/stable/tutorial/gpu.html).

**Comment by ycjing** [comment]
@ttoinou @yusuketomoto Thank you very much! I'll have a try.
