### ISSUE TITLE
Generating images takes 15 minutes

### ISSUE THREAD

**Issue by vermapratyush** [yusuketomoto/chainer-fast-neuralstyle#47]
On AWS machine (g2.2xlarge), I am trying to generate an image based on the model.
The command I execute is:
````
Testing - Takes around 15 minutes
python generate.py sample_images/tubingen.jpg -m models/composition.model -o sample_images/output.jpg
````
I haven't used MS-COCO anywhere as I am using the existing model.
From what I read in README, this should take ~1 second, however it takes 15 minutes.

Here are the steps that I followed (nothing new, just followed the readme):
1. Git Clone
2. Setup model "sh setup_model.sh"
3. Generate image.

**Comment by DylanAlloy** [comment]
On a Titan X it takes 1 second. This is a far superior card to what Amazon has available. Their cards are 2 generations old and have 1/3rd of the graphics memory. The GPU instances on AWS are their most limited, but I've been talking to them and they're working on it.

**Comment by markz-nyc** [comment]
try add -g 0?

**Comment by vermapratyush** [comment]
Adding -g to the generate.py worked. Thanks @markz-nyc 
However, it gave 'cudaErrorMemoryAllocation: out of memory'. With a smaller image it worked fine as mentioned in #3
