### ISSUE TITLE
train.py --resume', '-r' ? Cant find a training Example anywhere google

### ISSUE THREAD

**Issue by vic8760** [yusuketomoto/chainer-fast-neuralstyle#54]
The reason i ask is because im going to crunch the COCO dataset and its going to take 44hours, if there is a resume feature, it would be nice to resume post-work thats been trained. Thx

P.S any example of usage would be great
My Current cmd Setup
python train.py -s style.jpg -d train2014/ -g 0

**Comment by artnose** [comment]
Trying to find the same thing.   I'm pretty sure you want every 5k iterations saved    " -c 5000 " option
.. I don't know what the resume flag is looking for, maybe a saved iteration?

**Comment by artnose** [comment]
Looks like it wants the model file to start with.  so if you have saved the iterations, you might use something like :     -r  style_0_1000.model

**Comment by vic8760** [comment]
ok, i think i got it, thx!

**Comment by 6o6o** [comment]
The `-i` and `-r` switches provide the saved model file and optimizer state respectively, allowing you to resume your training later on, so it should be `-i style.model -r style.state`
