### ISSUE TITLE
Attempting to re-create starrynight.model

### ISSUE THREAD

**Issue by kirilledelman** [yusuketomoto/chainer-fast-neuralstyle#7]
Hi guys, big thanks to the authors for making this available - @yusuketomoto 

I'm having a hard time getting any sort of useful result.

I decided to try and rebuild a model file similar to the one that's bundled with code.

First of all, when running the trainer, with 

`python train.py -s sample_images/style.jpg -d models` 

it outputs 

`num traning images: 0`

but trains and outputs the model after 2 default epochs. I looked in the code and saw that it searches --dataset / -d directory for .jpg or .png files. This is confusing. I thought that directory was used for output? So I placed style.jpg into both /models and /sample_images

So, trying to get it to run, I made a file I can tweak and run from command line. I copied all the default param values from train.py as parameters for tweaking. No matter what I change the values to, the result is always complete garbage.

```
python train.py \
--style_image sample_images/style.jpg \
--dataset models \
--batchsize 1 \
--lambda_tv 10e-4 \
--lambda_feat 1e0 \
--lambda_style 1e1 \
--epoch 2 \
--lr 1e-3   

python generate.py \
sample_images/tubingen.jpg \
-m models/out.model \
-o sample_images/output.jpg
```

Output:
![output](https://cloud.githubusercontent.com/assets/6539713/16719281/089b9a90-46ee-11e6-9630-22ec088c28ed.jpg)

Has anyone been able to get this to work? What params should I use to re-create starrynight model?

I would appreciate any feedback.

**Comment by ttoinou** [comment]
You have to download the dataset MS coco train 2014 zip !

**Comment by ttoinou** [comment]
If ou only process 0 or too few images you'll have this glitchy picture !
